### PR TITLE
First Version (DIN, ISO15118-2 & -20, V2GTP) 

### PR DESCRIPTION
**Pull request by SebaLukas**
Added generated code from cbexigen, cmakelists.txt and a simple test to test the library

### CODE REVIEW

**Comment by barsnick** [comment]
Interestingly, libcb_v2gtp.so is alledgedly linked statically, when building dynamic libs:

```
$ cmake .. -DBUILD_SHARED_LIBS=on
...
$ make -j4
...
$ ldd ./build/lib/cbv2g/libcb_v2gtp.so 
	statically linked
```
It turns out it doesn't need any libc functions, and is therefore not linked against anything at all?
```
$ objdump -p ./build/lib/cbv2g/libcb_v2gtp.so | grep NEEDED
$
```

LGTM so far.

I cannot build tests though, some dependency is missing:
```
$ cmake .. -DBUILD_SHARED_LIBS=on -DCB_V2G_BUILD_TESTS=on
...
$ make
...
Scanning dependencies of target test_app_handshake
[ 99%] Building CXX object tests/app_handshake/CMakeFiles/test_app_handshake.dir/app_handshake.cpp.o
[100%] Linking CXX executable test_app_handshake
/usr/bin/ld: CMakeFiles/test_app_handshake.dir/app_handshake.cpp.o: undefined reference to symbol 'exi_bitstream_init'
/usr/bin/ld: /home/intech/Development/EVerest/libcbv2g/build/lib/cbv2g/libcb_exi_codec.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tests/app_handshake/CMakeFiles/test_app_handshake.dir/build.make:87: tests/app_handshake/test_app_handshake] Error 1
make[1]: *** [CMakeFiles/Makefile2:1175: tests/app_handshake/CMakeFiles/test_app_handshake.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
It does work without `-DBUILD_SHARED_LIBS=on` (and the test passes).

**Comment by barsnick** [comment]
`make test` now works with your latest commit, excellent.

PR LGTM. 👍

**Review by barsnick — APPROVED** [review]

**Comment by SebaLukas** [comment]
First point: That's interesting, on my system libc is used for libcb_v2gtp.so.
```
objdump -p build/lib/cbv2g/libcb_v2gtp.so | grep NEEDED
  NEEDED               libc.so.6
```
I use Fedora 39 (make and ninja makes no difference).  No idea why this happens.

**Comment by barsnick** [comment]
> I use Fedora 39 (make and ninja makes no difference). No idea why this happens.

I checked this on Ubuntu 20 (linking with _cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0_) and Ubuntu 22 (linking with _cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0_).

It doesn't really matter, of course, if it works. Out of pure interest, it would be fun to see the disassembled code(s).

P.S.: Lots of ❤ for Fedora.

**Pull request merged**
