### PR TITLE
Fix evc_setup_package name

### PR DESCRIPTION
**Pull request by SebaLukas**
## Describe your changes
 evc_setup_package adjusted so that it works like the other Everest libs

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Review by barsnick — APPROVED** [review]
I don't see a consistency across EVerest libs - libfsm, libiso15118 and libslac are also different - but otherwise LGTM.

https://github.com/EVerest/libfsm/blob/0c796dbc5cae110f2a08acc56f7f0234ffde82f1/CMakeLists.txt#L63-L65

https://github.com/EVerest/libiso15118/blob/61735ab20df675a77136eea69f84ca5bcc0a5a46/CMakeLists.txt#L58-L60

https://github.com/EVerest/libslac/blob/40a3554d83eabc0ae9f69314a6fa2236fa76c984/CMakeLists.txt#L54-L56

**Comment by SebaLukas** [comment]
I will adjust libiso right now. The other two could also be changed in the future.

**Comment by a-w50** [comment]
Do we actually have any guidelines, how to name these?  I usually tried to only prefix with everest, if it is tightly coupled to everest.  But if it could be reused without everest, I don't see why we should prefix everything with everest.

**Comment by barsnick** [comment]
> But if it could be reused without everest, I don't see why we should prefix everything with everest.

I agree, I see non-EVerest use for some of these, especially libcbv2g. I think you nail the problem.

**Comment by SebaLukas** [comment]
Your points are valid. I created a PR to revert this commit #9

**Pull request merged**
