### PR TITLE
Adding big int support

### PR DESCRIPTION
**Pull request by SebaLukas**
## Describe your changes
Generated code from https://github.com/EVerest/cbexigen/pull/87 to support BigInt encoding and decoding.

## Issue ticket number and link
libcbv2g could not decode the CertificateInstalltionReq message. See this issue https://github.com/EVerest/cbexigen/issues/54 for more details. 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Comment by hikinggrass** [comment]
This should probably also bump the project version to something >0.2 ( https://github.com/EVerest/libcbv2g/blob/784b3a58320adf999bc5208dbd7c80c1858a2124/CMakeLists.txt#L4 )

**Comment by barsnick** [comment]
> This should probably also bump the project version to something >0.2

I agree.

Also, the origin hash needs to be updated:
https://github.com/EVerest/libcbv2g/blob/feat/use_big_integer/CMakeLists.txt#L19

**Comment by barsnick** [comment]
Okay for me if it works in your SILs. I have no regressions in my (66) ISO 15118-2 samples, but they don't include any big integer examples.

Please fix the CMakeLists.txt though.

**Comment by hikinggrass** [comment]
> Okay for me if it works in your SILs. I have no regressions in my (66) ISO 15118-2 samples, but they don't include any big integer examples.
> 
> Please fix the CMakeLists.txt though.

I've updated the hash (and added that it's from a unmerged branch) and bumped the version to 0.2.1, is that what you had in mind?

**Review by barsnick — APPROVED** [review]

**Comment by barsnick** [comment]
> I've updated the hash (and added that it's from a unmerged branch) and bumped the version to 0.2.1, is that what you had in mind?

Exactly. Thanks!

**Pull request merged**
